apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: webpack-template
  annotations:
    github.com/project-slug: Ilya-Baklanov/webpack-template
spec:
  type: other
  lifecycle: unknown
  owner: Ilya-Baklanov
